### ISSUE TITLE
[feature request] search projection by name or code

### ISSUE THREAD

**Issue by lnicola** [OSGeo/PROJ-CRS-Explorer#1]
This is a really nice project, congrats!

I do have one feature suggestion, though: it would be useful if you could search projections by their name or code.

**Comment by jjimenezshaw** [comment]
Thanks @lnicola .

Probably you can do it in https://epsg.org/search/by-name (where they have the full db in the backend).
Could you send me an example of the projections that you want to find? However, I do not think it would be (pre)exportable with `pyproj` (this project is a static page reading the data from a json file).

**Comment by lnicola** [comment]
It should be possible to make an index and do the search client-side, but I agree, it might be too much of a hassle.

Searching the EPSG site works for me, although it's much slower.

**Comment by jjimenezshaw** [comment]
@lnicola Re-reading your request, I realized that there is a field in the [json file](https://raw.githubusercontent.com/jjimenezshaw/crs-explorer/master/crslist.json) called "projection_method_name", that has only the name, like
```
  {
    "auth_name": "EPSG",
    "code": "3025",
    "name": "RT38 7.5 gon V",
    "type": "PROJECTED_CRS",
    "deprecated": false,
    "area_of_use": [
      10.93,
      57.29,
      12.91,
      59.73,
      "Sweden - communes west of approximately 12\u00b026'E. See information source for map."
    ],
    "projection_method_name": "Transverse Mercator"
  },
  ```
  I can add an extra column, and maybe later a search on it. See that there is no projection code, just "that name". Would that be useful, or is it too generic?

**Comment by lnicola** [comment]
> See that there is no projection code, just "that name". Would that be useful, or is it too generic?

The projection code is there in the authority name and code fields, so it's EPSG:3025. I think searching for the code instead of the name would be more useful to me, but searching by name could also be nice.

Anyway, this isn't trivial to implement, so don't worry too much about it.
